### PR TITLE
Fix #124: adapt to GHC-8.0.1.

### LINKED ISSUE #124: adapt to GHC-8.0.1
Using `ghc-8.0.0.20160109` I get:
~~~~
Preprocessing library reactive-banana-1.1.0.0...
[ 1 of 22] Compiling Reactive.Banana.Prim.Util ( src/Reactive/Banana/Prim/Util.hs, dist/build/Reactive/Banana/Prim/Util.o )

src/Reactive/Banana/Prim/Util.hs:54:25: error:
    • Couldn't match expected type ‘GHC.State# GHC.RealWorld
                                    -> (# GHC.State# GHC.RealWorld, c0 #)’
                  with actual type ‘IO ()’
    • In the third argument of ‘GHC.mkWeak#’, namely ‘f’
      In the expression: GHC.mkWeak# r# v f s
      In the expression:
        case GHC.mkWeak# r# v f s of {
          (# s1, w #) -> (# s1, GHC.Weak w #) }
Failed to install reactive-banana-1.1.0.0
~~~~

### PR DESCRIPTION
**Pull request by vagarenko**
Now builds with GHC 8.0.1

They changed GHC.Prim.mkWeak# signature from:
`mkWeak# :: o -> b -> c -> State# RealWorld -> (#State# RealWorld, Weak# b#)`
to: 
`mkWeak# :: o -> b -> (State# RealWorld -> (#State# RealWorld, c#)) -> State# RealWorld -> (#State# RealWorld, Weak# b#)`
Basically `c` type variable is now unpacked IO value.

### CODE REVIEW

**Comment by HeinrichApfelmus** [comment]
Much appreciated, thanks a lot!
